# Generated by Django 2.2 on 2019-04-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru', max_length=5, verbose_name='Language'),
        ),
    ]
