# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='content.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='template',
            field=models.CharField(choices=[('content_view', 'View single page'), ('content_list', 'List pages')], default='content_view', max_length=100, verbose_name='Template'),
        ),
    ]
