# Generated by Django 4.1.5 on 2023-02-05 23:50

from django.db import migrations, models
import vcms.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20211102_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='json',
            field=models.JSONField(default=vcms.content.models.default_json, editable=False, verbose_name='Json content'),
        ),
    ]
