# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20160911_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(blank=True, to='content.Category', verbose_name='Category'),
        ),
    ]
