# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20161229_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comments',
            field=models.BooleanField(default=False, verbose_name='Allow comments'),
        ),
    ]
