# Generated by Django 2.1.4 on 2018-12-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mime', models.CharField(blank=True, max_length=128, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('uuid', models.CharField(default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Plain text'), ('python', 'Python'), ('php', 'PHP'), ('bash', 'Bash'), ('html', 'HTML'), ('django', 'Django'), ('smarty', 'Smarty'), ('mysql', 'Mysql'), ('postgresql', 'Postgresql'), ('csharp', 'C#'), ('lua', 'Lua'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('tcl', 'Tcl'), ('scheme', 'Scheme'), ('xml', 'XML')], db_index=True, default='text', max_length=10, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='share')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('password', models.CharField(blank=True, db_index=True, max_length=64)),
                ('disabled', models.BooleanField(db_index=True, default=False)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('thumbnail', models.CharField(editable=False, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('time_delete', models.DateField(blank=True, default=None, null=True)),
                ('content_html', models.TextField(blank=True, editable=False, null=True)),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_share', to='share.Share'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
