# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='time_delete',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='share',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
