# Generated by Django 2.2.3 on 2019-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Original file name'),
        ),
    ]
