# Generated by Django 2.2.6 on 2019-10-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_share_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='personal',
            field=models.BooleanField(default=False, verbose_name='Personal'),
        ),
    ]
