# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20161229_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='time_delete',
            field=models.DateField(blank=True, default=None),
        ),
    ]
