# Generated by Django 3.2.9 on 2021-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20211102_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='expired_on',
            field=models.DateField(blank=True, null=True, verbose_name='Expired on'),
        ),
    ]
