# Generated by Django 2.2.6 on 2019-11-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_share_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='json',
            field=models.TextField(default='', verbose_name='Json content'),
        ),
    ]
