# Generated by Django 4.1.5 on 2023-02-05 23:50

from django.db import migrations, models
import vcms.share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='json',
            field=models.JSONField(default=vcms.share.models.default_json, verbose_name='Json content'),
        ),
    ]
