# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0004_auto_20161230_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mime', models.CharField(blank=True, max_length=128, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('uuid', models.CharField(default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_share', to='share.Share')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
